[colors]
color0      = "0x{base00}"
color1      = "0x{base01}"
color2      = "0x{base02}"
color3      = "0x{base03}"
color4      = "0x{base04}"
color5      = "0x{base05}"
color6      = "0x{base06}"
color7      = "0x{base07}"
color8      = "0x{base08}"
color9      = "0x{base09}"
color10     = "0x{base0A}"
color11     = "0x{base0B}"
color12     = "0x{base0C}"
color13     = "0x{base0D}"
color14     = "0x{base0E}"
color15     = "0x{base0F}"
