[colors]
color0      = "0x282828"
color1      = "0x3c3836"
color2      = "0x504945"
color3      = "0x665c54"
color4      = "0xbdae93"
color5      = "0xd5c4a1"
color6      = "0xebdbb2"
color7      = "0xfbf1c7"
color8      = "0xfb4934"
color9      = "0xfe8019"
color10     = "0xfabd2f"
color11     = "0xb8bb26"
color12     = "0x8ec07c"
color13     = "0x83a598"
color14     = "0xd3869b"
color15     = "0xd65d0e"

