---
- name: Deploy desktop environment
  hosts: local
  vars:
    the_user: "{{ ansible_facts['env']['USER']}}"
    user_home_dir: "{{ ansible_facts['env']['HOME']}}"
  tasks:
    # Inform which machine local user we're installing this for
    - name: Print username
      ansible.builtin.debug:
        msg: "Setting up the desktop environment for {{ the_user }} and home dir {{user_home_dir}}"

    # Set up dotfiles alias (git)
    # i.e. git df status
    - name: Set up git dotfiles alias
      ansible.builtin.git_config:
        name: alias.df
        scope: global
        value: "!git --git-dir=$HOME/dotfiles.git/ --work-tree=$HOME"
        state: present

    # Setup the fish shell
    - name: Setup the fish shell
      become: true
      block:
        - name: Ensure fish is installed
          ansible.builtin.package:
            name: fish
            state: present
        - name: Change default shell to fish
          ansible.builtin.user:
            name: "{{ the_user }}"
            shell: /bin/fish

    # Create symlink to prefered light mode wallpaper
    - name: Symlink current wallpaper
      ansible.builtin.file:
        src: "$HOME/.local/share/wallpapers/light/light_mojave.jpg"
        path: "$HOME/.wallpaper"
        state: link

    # Create symlink to prefered light mode colorscheme
    - name: Symlink current colors
      ansible.builtin.file:
        src: "$HOME/.config/cfx/light"
        path: "$HOME/.color.d"
        state: link

    # Install required packages
    - name: Install required packages
      become: true
      block:
        - name: Installing system packages
          ansible.builtin.package:
            name: "{{item}}"
            state: present
          loop: "{{pkgs}}"
          register: pkgs_install_res
        - name: Ensuring flatpak is installed
          ansible.builtin.package:
            name: flatpak
            state: present
        - name: Add Flathub remote repository
          community.general.flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        - name: Installing flatpak apps
          community.general.flatpak:
            name: "{{item}}"
            state: present
          loop: "{{pkgs_flatpaks}}"
          register: pkgs_flatpaks_install_res

    # Set up greetd systemd service
    - name: Setup greetd
      become: true
      block:
        - name: Ensure greetd is installed
          ansible.builtin.package:
            name: greetd
            state: present
        - name: Copy greetd config
          ansible.builtin.copy:
            src: "{{user_home_dir}}/.config/greetd/config.toml.src"
            dest: "/etc/greetd/config.toml"
        - name: Disable current display manager
          ansible.builtin.systemd:
            name: display-manager
            enabled: false
          failed_when: false
        - name: Enable and start greetd
          ansible.builtin.systemd:
            name: greetd.service
            state: started
            enabled: true

